name = "newmarket"
compatibility_date = "2026-02-09"
main = "dist/server/server.js"

[assets]
directory = "./dist/client"
binding = "ASSETS"

[vars]
NODE_ENV = "production"
BETTER_AUTH_SECRET = "onuXn"
